---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 15m
  url: https://metallb.github.io/metallb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-helm-chart-value-overrides
  namespace: metallb
data:
  config-values/metallb-values.yaml: |-  
    # <upstream values go here>
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: metallb
  valuesFrom:
  - kind: ConfigMap
    name: metallb-helm-chart-value-overrides
    valuesKey: config-values/metallb-values.yaml # This is the default, but best to be explicit for clarity