apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.14.8"   # Adjust the version as needed
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 172.18.0.100-172.18.0.200  # Adjust to match your environment's IP range
