apiVersion: metallb.io/v1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb
spec:
  addresses:
  - 172.18.0.0/16
---
apiVersion: metallb.io/v1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisment
  namespace: metallb
spec:
  ipAddressPools:
  - metallb-pool 
  aggregationLength: 32
  localPref: 100
  communities:
  - 65535:65282