name: k8s cluster CI and tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.7.0
        with:
          cluster_name: flux

      - name: Determine Branch
        run: |
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              BRANCH=${{ github.head_ref }}
            else
              BRANCH=${{ env.BRANCH }}
            fi

      - name: Install Flux in Kubernetes Kind
        run: flux install

      - name: Setup cluster reconciliation
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=$BRANCH \
          --username=${GITHUB_ACTOR} \
          --password=${{ secrets.GHT }} \
          --ignore-paths="clusters/**/flux-system/"
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./flux/bootstrap
          
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait kustomization/flux-system --for=condition=ready --timeout=2m
          kubectl -n flux-system wait kustomization/metallb--metallb-system --for=condition=ready --timeout=2m
          
      - name: Verify helm reconciliation
        run: |
          kubectl -n podinfo wait helmrelease/podinfo --for=condition=ready --timeout=2m
          kubectl -n metallb-system wait helmrelease/metallb --for=condition=ready --timeout=2m
          
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces
